"""Honest evaluation of the trained ATOShield model.

Scores the labeled test set with the SAME pipeline used at serving time
(scaler -> isolation forest -> calibration), then reports a real confusion
matrix, precision / recall / F1 at the operating threshold, ROC-AUC, and a
precision/recall-vs-threshold plot. Results are written to
``ml/artifacts/eval_report.md`` — those are the only numbers that may appear in
the project report.
"""

from __future__ import annotations

import json
import os

import joblib
import numpy as np
import pandas as pd

import matplotlib
matplotlib.use("Agg")  # headless
import matplotlib.pyplot as plt  # noqa: E402

from sklearn.metrics import (  # noqa: E402
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    precision_recall_curve,
    roc_curve,
)

import features as F  # noqa: E402

HERE = os.path.dirname(__file__)
DATA_DIR = os.path.join(HERE, "data")
ART_DIR = os.path.join(HERE, "artifacts")

OPERATING_THRESHOLD = 60  # the "alert" cutoff; tunable in backend config

RAW_COLUMNS = [
    "login_hour", "ip_change", "device_change", "frequency", "geo_velocity", "failed_attempts",
]


def main() -> None:
    test_path = os.path.join(DATA_DIR, "labeled_test.parquet")
    if not os.path.exists(test_path):
        raise SystemExit(f"Missing {test_path}. Run generate_dataset.py first.")

    model = joblib.load(os.path.join(ART_DIR, "model.pkl"))
    scaler = joblib.load(os.path.join(ART_DIR, "scaler.pkl"))
    with open(os.path.join(ART_DIR, "calibration.json"), encoding="utf-8") as fh:
        calib = json.load(fh)

    df = pd.read_parquet(test_path)
    X = F.rows_to_matrix(df[RAW_COLUMNS].to_dict("records"))
    Xs = scaler.transform(X)
    decision = model.decision_function(Xs)
    risk = np.array([F.apply_calibration(d, calib) for d in decision])

    y_true = df["is_attack"].to_numpy().astype(int)
    y_pred = (risk >= OPERATING_THRESHOLD).astype(int)

    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    # ROC-AUC uses the continuous risk score (threshold-independent).
    auc = roc_auc_score(y_true, risk)

    # Per-attack-type recall (honesty: slow-burn is hard).
    per_type = {}
    for t in sorted(df.loc[df.is_attack == 1, "attack_type"].unique()):
        mask = (df["attack_type"] == t).to_numpy()
        per_type[t] = {
            "n": int(mask.sum()),
            "recall": float(y_pred[mask].mean()),
        }

    # Plots
    prec_curve, rec_curve, thr = precision_recall_curve(y_true, risk)
    fpr, tpr, _ = roc_curve(y_true, risk)

    fig, ax = plt.subplots(1, 2, figsize=(12, 5))
    ax[0].plot(thr, prec_curve[:-1], label="precision")
    ax[0].plot(thr, rec_curve[:-1], label="recall")
    ax[0].axvline(OPERATING_THRESHOLD, color="gray", ls="--", label=f"op={OPERATING_THRESHOLD}")
    ax[0].set_xlabel("risk threshold")
    ax[0].set_ylabel("score")
    ax[0].set_title("Precision / Recall vs threshold")
    ax[0].legend()
    ax[0].grid(alpha=0.3)

    ax[1].plot(fpr, tpr, label=f"ROC (AUC={auc:.3f})")
    ax[1].plot([0, 1], [0, 1], ls="--", color="gray")
    ax[1].set_xlabel("false positive rate")
    ax[1].set_ylabel("true positive rate")
    ax[1].set_title("ROC curve")
    ax[1].legend()
    ax[1].grid(alpha=0.3)

    fig.tight_layout()
    plot_path = os.path.join(ART_DIR, "pr_threshold.png")
    fig.savefig(plot_path, dpi=120)
    plt.close(fig)

    # Report
    report = f"""# ATOShield — Model Evaluation Report

_Generated by `ml/evaluate.py`. These are the only metrics that may be quoted in
the project report._

## Dataset
- Test events: **{len(df):,}**
- Attacks (positives): **{int(y_true.sum()):,}**
- Benign (negatives): **{int((y_true == 0).sum()):,}**

## Operating point (risk threshold = {OPERATING_THRESHOLD})

| Metric | Value |
|---|---|
| Precision | **{precision:.3f}** |
| Recall    | **{recall:.3f}** |
| F1        | **{f1:.3f}** |
| ROC-AUC   | **{auc:.3f}** |

### Confusion matrix
|               | Pred benign | Pred attack |
|---------------|-------------|-------------|
| **Actual benign** | {tn} (TN) | {fp} (FP) |
| **Actual attack** | {fn} (FN) | {tp} (TP) |

## Recall by attack type
| Attack type | N | Recall |
|---|---|---|
"""
    for t, v in per_type.items():
        report += f"| {t} | {v['n']} | {v['recall']:.3f} |\n"

    report += f"""
## Notes (honest)
- The model is unsupervised; it was trained on benign data only and never saw
  these labels. ROC-AUC is computed on the continuous calibrated risk.
- `slow_burn` attacks flip a single behavioral signal at a time and are the
  hardest class — low recall there is expected and is reported, not hidden.
- The threshold is configurable in the backend (`ALERT_THRESHOLD`); raising it
  trades recall for precision. See `pr_threshold.png`.

![Precision/Recall vs threshold and ROC](pr_threshold.png)
"""

    with open(os.path.join(ART_DIR, "eval_report.md"), "w", encoding="utf-8") as fh:
        fh.write(report)

    print("=" * 60)
    print("ATOShield evaluation @ threshold", OPERATING_THRESHOLD)
    print("=" * 60)
    print(f"Confusion matrix:\n  TN={tn} FP={fp}\n  FN={fn} TP={tp}")
    print(f"Precision={precision:.3f}  Recall={recall:.3f}  F1={f1:.3f}  ROC-AUC={auc:.3f}")
    print("Per-type recall:", {k: round(v["recall"], 3) for k, v in per_type.items()})
    print(f"Report -> {os.path.join(ART_DIR, 'eval_report.md')}")


if __name__ == "__main__":
    main()
